### ISSUE TITLE
#环境

### ISSUE THREAD

**Issue by dxkube** [crushr/VGG-BERT_CAT#2]
你好，感谢您的代码开源，可以问一下transformer版本吗？我遇到了一些bug

**Comment by dxkube** [comment]
TypeError: __init__() got an unexpected keyword argument 'return_dict' 我报了这个错误

**Comment by crushr** [comment]
bert base-uncased & bert base-chinese

**Comment by dxkube** [comment]
这个我知道，但是后面这个return_dict参数报错了，我就在想是不是我transformers版本太低了，我用的2.1版本

**Comment by crushr** [comment]
我用的是4.5.1

**Comment by dxkube** [comment]
非常感谢你，我刚刚换成了3.4.0版本，现在已经在运行了，谢谢

**Comment by crushr** [comment]
ok
